import Head from 'next/head';

import {Inter} from '@next/font/google';
import styles from '../styles/Home.module.css';

const inter = Inter({subsets: ['latin']});

export default function Home({children}: {children: React.ReactNode}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="relative flex h-[500vh] w-full flex-col items-center justify-center bg-stone-900 text-3xl text-white">
          <ul className="absolute flex h-full flex-col items-center justify-between p-20">
            <li> This is a really long div...</li>
            <li>Halfway there!</li>
            <li>👋</li>
          </ul>
        </div>
      </main>
    </>
  );
}
